#!/bin/bash
# An executable script to run in foreground and manage colima
# See:
#   - https://github.com/abiosoft/colima/issues/96
#   - https://gist.github.com/fardjad/a83c30b9b744b9612d793666f28361a5
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

function shutdown() {
  colima stop
  exit 0
}

trap shutdown SIGTERM
trap shutdown SIGKILL
trap shutdown SIGINT

# wait until colima is running
while true; do
  colima status &>/dev/null
  if [[ $? -eq 0 ]]; then
    break;
  fi

  colima start
  sleep 5
done

tail -f /dev/null &
wait $!
